name: e0
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch-scatter
  - tqdm
  - pip:
    - einops
    - wandb
    - lpips
    - laspy
    - jaxtyping
    - colorama
    - opencv-python

